name: Deploy React App

on:
  push:
    branches:
      - main  # Change to master if your default branch is master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build
